services:
    app:
        image: app2
        restart: on-failure
        depends_on:
            - banco
        ports:
            - 3000:3000
        networks: [minharede]

    banco:
        image: postgres:14.5
        hostname: banco-1
        ports:
            - 5432:5432
        networks: [minharede]
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: docker
        


networks:
    minharede:
        driver: bridge
